doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: 'mysql://%env(DB_USER)%:%env(DB_PASSWORD)%@%env(DB_HOST)%:%env(DB_PORT)%/%env(DB_NAME)%?serverVersion=%env(DB_VERSION)%'
                driver: pdo_mysql
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_general_ci
                    engine: InnoDB
                #server_version: '15'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                query_cache_driver:
                    type: pool
                    pool: doctrine.query_cache_pool
                connection: default
                report_fields_where_declared: true
                naming_strategy: doctrine.orm.naming_strategy.default
                auto_mapping: true
                validate_xml_mapping: true
                identity_generation_preferences:
                    Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
                mappings:
                    App:
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        is_bundle: false
                        prefix: 'App\Entity'
                        alias: App
                dql:
                    string_functions:
                        MATCH_AGAINST: App\Service\Doctrine\MatchAgainst
#                        MONTH: Oro\ORM\Query\AST\Functions\SimpleFunction
#                        YEAR: Oro\ORM\Query\AST\Functions\SimpleFunction
#                        # https://github.com/oroinc/doctrine-extensions
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@local:
    doctrine:
        dbal:
            logging: true
            profiling: true
#            connections:
#                direct:
#                    url: 'mysql://%env(DB_USER_DIRECT)%:%env(DB_PASSWORD_DIRECT)%@%env(DB_HOST_DIRECT)%:%env(DB_PORT_DIRECT)%/%env(DB_NAME_DIRECT)%'
        orm:
            auto_generate_proxy_classes: true
#            entity_managers:
#                direct:
#                    connection: direct

when@dev:
    doctrine:
        orm:
            auto_generate_proxy_classes: true

when@preprod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
