# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

knp_paginator:
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'