# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'

when@local:
    framework:
        mailer:
            envelope:
                recipients: ['dev@agence-felix.fr']

when@dev:
    framework:
        mailer:
            envelope:
                recipients: ['dev@agence-felix.fr']