# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

framework:
    default_locale: '%env(APP_LOCALE)%'
    enabled_locales: ['fr']
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: ['%locale%']
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
#            phrase:
#                dsn: '%env(PHRASE_DSN)%'